---
abstract: 'Convert HTML Files to be used on a hard disk'
author:
  - unknown
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
keywords:
  - hard-disk
  - html
  - index
  - links
  - local
  - localise
  - localize
  - view
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Links-Localize
provides:
  HTML::Links::Localize:
    file: lib/HTML/Links/Localize.pm
    version: v0.2.7
requires:
  HTML::Parser: 0
  strict: 0
  warnings: 0
resources:
  license: http://www.opensource.org/licenses/mit-license.php
  repository: http://bitbucket.org/shlomif/perl-html-links-localize
version: v0.2.7
